# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = []
description = "A simple geographical service"
language = "javascript"
manifest_version = 2
name = "geo-service"
service_id = "â€¦"

[scripts]
  build = "npm exec webpack && npm exec js-compute-runtime ./bin/index.js ./bin/main.wasm"
